# Generated by Django 6.0 on 2025-12-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_pack_previous_ticket_alter_business_id_alter_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='current_location',
            field=models.PositiveSmallIntegerField(blank=True, max_length=100, null=True),
        ),
    ]
